Repository ynput/ayon-harmony, pull requests merged in 2024-12, with the labels that each got.

#14 Refactor legacy `avalon` and `pype` to `AYON`
  client/ayon_harmony/api/README.md
  client/ayon_harmony/api/TB_sceneOpened.js
  client/ayon_harmony/api/__init__.py
  client/ayon_harmony/api/js/AyonHarmonyAPI.js
  client/ayon_harmony/api/js/package.json
  client/ayon_harmony/api/lib.py
  client/ayon_harmony/api/pipeline.py
  client/ayon_harmony/api/plugin.py
  client/ayon_harmony/api/workio.py
  client/ayon_harmony/js/AyonHarmony.js
  client/ayon_harmony/js/README.md
  client/ayon_harmony/js/creators/CreateRender.js
  client/ayon_harmony/js/loaders/ImageSequenceLoader.js
  client/ayon_harmony/js/loaders/TemplateLoader.js
  client/ayon_harmony/js/package.json
  client/ayon_harmony/js/publish/CollectCurrentFile.js
  client/ayon_harmony/js/publish/CollectFarmRender.js
  client/ayon_harmony/js/publish/CollectPalettes.js
  client/ayon_harmony/js/publish/ExtractPalette.js
  client/ayon_harmony/js/publish/ExtractTemplate.js
  client/ayon_harmony/plugins/create/create_farm_render.py
  client/ayon_harmony/plugins/create/create_render.py
  client/ayon_harmony/plugins/load/load_background.py
  client/ayon_harmony/plugins/load/load_imagesequence.py
  client/ayon_harmony/plugins/load/load_palette.py
  client/ayon_harmony/plugins/load/load_template.py
  client/ayon_harmony/plugins/publish/collect_current_file.py
  client/ayon_harmony/plugins/publish/collect_farm_render.py
  client/ayon_harmony/plugins/publish/collect_palettes.py
  client/ayon_harmony/plugins/publish/collect_scene.py
  client/ayon_harmony/plugins/publish/extract_palette.py
  client/ayon_harmony/plugins/publish/extract_template.py
  client/ayon_harmony/plugins/publish/validate_scene_settings.py
  server/settings/publish_plugins.py
Labels: type: maintenance

#15 Remove entityType from context settings
  client/ayon_harmony/api/pipeline.py
  client/ayon_harmony/plugins/publish/validate_scene_settings.py
Labels: type: bug

#16 Use context settings from task instead of folder entity
  client/ayon_harmony/api/pipeline.py
Labels: type: enhancement

#19 Use Publisher instead of pyblish pype
  client/ayon_harmony/api/TB_sceneOpened.js
  client/ayon_harmony/api/__init__.py
  client/ayon_harmony/api/lib.py
  client/ayon_harmony/api/pipeline.py
  client/ayon_harmony/api/plugin.py
Labels: type: enhancement, bump minor
