Repository ynput/ayon-harmony, pull requests merged in 2025-10, with the labels that each got.

#77 Render: Make sure filename does not end with number
  client/ayon_harmony/plugins/publish/extract_render.py
Labels: type: bug

#78 Chore: Formatting changes
  client/ayon_harmony/api/lib.py
  client/ayon_harmony/hooks/pre_launch_args.py
Labels: type: enhancement

#75 Feature: Instance active state stored to nodes only for render
  client/ayon_harmony/api/plugin.py
Labels: type: feature, community
